name: PlayerParticles
main: com.esophose.playerparticles.PlayerParticles
version: ${project.version}
api-version: 1.13
description: Display particles around your player and blocks using customized styles and data!
author: Esophose
website: https://www.spigotmc.org/resources/playerparticles.40261/
commands:
    pp:
        description: The main PlayerParticles command. By default, opens the GUI.
        aliases:
        - particles
        - trails
        - pparticles
    ppo: 
        description: Allows executing a /pp command for another player.
        permission: playerparticles.other
